---
title: "Viet History"
author: "Duc Du"
date: '2022-08-30'
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls(all.names = TRUE))
knitr::opts_chunk$set(echo = FALSE, 
                      cache=TRUE,
                      tidy.opts=list(width.cutoff=60),
                      tidy=TRUE)
#library(rmarkdown)
#library(knitr)
library(markdown)

library(stringr)
library(forcats)
library(RColorBrewer)
library(tidyverse)
library(dplyr)

library(ggplot2)
library(Hmisc)
library(gtsummary)
#library(flextable)
library(huxtable)

library(data.table)
library(lubridate)
library(stringi)

library(psych) # for describing the data
library(tableone)
#library(compareGroups)
library(forcats)
library(ggpubr)
library(rstatix)

#library(dlookr)
#library(flextable)

library(haven)

library(raster)
library(rgdal)
library(viridis)

select<-dplyr::select
filter<-dplyr::filter
recode<-dplyr::recode
getData<-raster::getData

# rotate function (see here: https://r-spatial.github.io/sf/articles/sf3.html#affine-transformations
rot <- function(a) matrix(c(cos(a), sin(a), -sin(a), cos(a)), 2, 2)

options(scipen=999, digits = 3)
options(max.print=1000000)
```

## Load data

```{r load data}
load("data/hoviet.RData")
```

## Inspecting data

```{r, echo=FALSE}
library(dplyr)
library(gapminder)

head(gapminder)
```

## Vietnam

```{r}
vietnam <- gapminder %>%
  filter(
    continent == "Asia",
    country == "Vietnam"
  )
head(vietnam)
```

## Plot the population of Vietnam for all years available.

```{r}
vietnam %>% ggplot(.,aes(x =year, y= pop)) +
  geom_line(color ='#1ABC9C') + geom_point(color='#21618C')
```
## What was the percent growth (or decline) in population in 2007?

```{r}
vietnam <- vietnam %>%
  mutate(PercentGrowth = (pop - lag(pop))*100/lag(pop),
         interval = (year - lag(year))) %>% 
  arrange(year)
head(vietnam)
```

## What has been the historical growth (or decline) in population for Vietnam?

```{r}
vietnam %>% mutate(PercentGrowth = (pop - lag(pop))*100/lag(pop)) %>% 
           ggplot(.,aes(x=year, y=PercentGrowth)) + geom_line(color ='#1ABC9C') + geom_point(color='#21618C')
```
